language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
script:
    - coverage run --source=toolium setup.py test
after_success:
    - coveralls
